### ISSUE TITLE
Question about program used

### ISSUE THREAD

**Issue by YisusChrist** [lxbx44/dotfiles#1]
Hello, I love the rice, it looks great!

I was wondering what is the task manager you are using in this [screenshot](https://github.com/lxbx44/dotfiles/blob/main/img%2F2.png). It looks similar to btop but I'm not sure. I've been using htop, bashtop and and btop for years but I've never seen something like this.

**Comment by lxbx44** [comment]
Hey! sorry for late reply. That task manager is bottom (btm)
